stages:
  - deploy

.build-and-push-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  when: manual
  script:
    - mkdir -p /kaniko/.docker
#    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "$CI_PROJECT_DIR/$CONTEXT_DIR" --skip-tls-verify --dockerfile $CI_PROJECT_DIR/$CONTEXT_DIR/Dockerfile --destination $REGISTRY_HOST/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA

build-and-push-image:sshd-with-docker-cli:
  extends: .build-and-push-image
  variables:
    CONTEXT_DIR: sshd-with-docker-cli
    DOCKER_IMAGE_NAME: sshd-with-docker-cli

build-and-push-image:ssh-client:
  extends: .build-and-push-image
  variables:
    CONTEXT_DIR: ssh-client
    DOCKER_IMAGE_NAME: ssh-client
